version: '3.9'

volumes:
  postgres_data: {}


services:
  hcs:
    build:
      context: ./hcs
    volumes:
      - ./hcs:/app
    command: /start.sh
    entrypoint: /entrypoint.sh
    restart: on-failure
    env_file:
      - ./hcs/.env.dev
    ports:
      - '4000:4000'
    depends_on:
      - db
      - redis

  db:
    image: postgres:12.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      LANG: ru_RU.UTF-8
      LANGUAGE: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8
    ports:
      - '5435:5435'
    command: -p 5435

  celery:
    build:
      context: ./hcs
    command: celery -A application worker -l info
    volumes:
      - ./hcs:/app
    env_file:
      - ./hcs/.env.dev
    depends_on:
      - db
      - redis

  celery-beat:
    build:
      context: ./hcs
    command: celery -A application beat -l info
    volumes:
      - ./hcs:/app
    env_file:
      - ./hcs/.env.dev
    depends_on:
      - db
      - redis

  celery-dashboard:
    build:
      context: ./hcs
    command: celery -A application flower  --address=0.0.0.0 --port=5566
    volumes:
      - ./hcs:/app
    ports:
      - '5566:5566'
    env_file:
      - ./hcs/.env.dev
    depends_on:
      - db
      - redis


  redis:
    image: redis:latest
    command: redis-server --port 6380
    ports:
      - '6380:6380'
    volumes:
      - ./hcs:/app
