# Generated by Django 3.2.8 on 2021-10-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True)),
                ('personal_acc_hcs', models.FloatField(default=0.0)),
                ('personal_acc_landline_phone', models.FloatField(default=0.0)),
                ('personal_acc_distance_phone', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
