# Generated by Django 3.2.8 on 2021-11-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(blank=True, verbose_name='date_of_birth'),
        ),
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='users',
            name='personal_acc_distance_phone',
            field=models.FloatField(default=0.0, verbose_name='personal_acc_distance_phone'),
        ),
        migrations.AlterField(
            model_name='users',
            name='personal_acc_hcs',
            field=models.FloatField(default=0.0, verbose_name='personal_acc_hcs'),
        ),
        migrations.AlterField(
            model_name='users',
            name='personal_acc_landline_phone',
            field=models.FloatField(default=0.0, verbose_name='personal_acc_landline_phone'),
        ),
    ]
