# Generated by Django 3.2.8 on 2021-12-06 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211206_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_units', models.FloatField(verbose_name='amount_units')),
                ('units', models.CharField(choices=[('m^2', 'square meters'), ('m^3', 'cubic meters'), ('Gcal', 'gigacalories'), ('m', 'minutes')], max_length=17, verbose_name='units')),
                ('amount_money', models.FloatField(verbose_name='amount_money')),
                ('period_of_receipt', models.DateField(verbose_name='period_of_receipt')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='users')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'ordering': ['period_of_receipt'],
            },
        ),
    ]
