# Generated by Django 3.2.8 on 2021-12-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_receipt_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='units',
            field=models.CharField(choices=[('m^2', 'square meters'), ('m^3', 'cubic meters'), ('Gcal', 'gigacalories'), ('minutes', 'minutes')], max_length=17, verbose_name='units'),
        ),
    ]
